Update workflow1.yml

diff --git a/.github/workflows/workflow1.yml b/.github/workflows/workflow1.yml
--- a/.github/workflows/workflow1.yml
+++ b/.github/workflows/workflow1.yml
@@ -15,12 +15,14 @@ jobs:
         run: |
           echo "Hello World" > Sample text.txt
           
-      - name: Commit and push changes
-        uses: stefanzweifel/git-auto-commit-action@v4
-        with:
-          commit_message: "Add content to sample text.txt"
-          commit_user_name: "Indhu1024"
-          commit_user_email: "indhuchandran10@gmail.com"
-
+   - name: Read file content
+        run: |
+          file_path="Sample text.txt"
+          if [ -f "$file_path" ]; then
+            cat "$file_path"
+          else
+            echo "File not found: $file_path"
+            exit 1
+          fi 
 
      
